version: 2
jobs:
  build:
    docker:
      - image: renegare/wcinv-ci:bd0ef7c
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make build
      - run: make push

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build